# Generated by Django 4.2.18 on 2025-04-23 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0712_add_message_template_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorTrackingAssignmentRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.UUIDT, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order_key", models.IntegerField()),
                ("bytecode", models.JSONField()),
                ("filters", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("disabled_data", models.JSONField(blank=True, null=True)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team")),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user_group",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="posthog.usergroup"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["team_id"], name="posthog_err_team_id_9da78b_idx")],
            },
        ),
    ]
